name: timesec
channels:
  - defaults
  - conda-forge
dependencies:
  - python >=3.11
  - numpy
  - scipy
  - colorlog
  - pycparser
  - frozendict
  - tqdm
  - matplotlib
  - tabulate
  - pip
  - pip:
    - typing-extensions
    - pynput
    - pydot
    - pyinterval
    - git+https://github.com/caterinaurban/apronpy.git@refs/pull/7/head
